name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0
    
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}
    
    - name: Install HolmesGPT
      run: |
        pip install holmesgpt
    
    - name: Deploy to EKS
      run: |
        # Apply Kubernetes manifests
        kubectl apply -f https://raw.githubusercontent.com/robusta-dev/kubernetes-demos/refs/heads/main/image_pull_backoff/no_such_image.yaml
        # Wait for rollout
        if ! kubectl rollout status deployment/app --timeout=300s; then
          echo "Deployment failed - starting HolmesGPT investigation"
          # Capture current state
          kubectl get all > deployment-state.txt
          kubectl describe deployment app >> deployment-state.txt
          kubectl get events --sort-by='.lastTimestamp' | tail -20 >> deployment-state.txt
          # Run HolmesGPT investigation and send directly to Slack
          cat deployment-state.txt | holmes ask \
            "🚨 EKS Deployment Failed in ${{ github.repository }}

            Environment: EKS Cluster ${{ vars.EKS_CLUSTER_NAME }} in ${{ vars.AWS_REGION }}
            Commit: ${{ github.sha }}
            Pipeline: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            The deployment failed. Analyze why the pods are not becoming ready. Focus on: image pulls, resource limits, probes, and configuration issues" \
            --no-interactive \
            --destination slack \
            --slack-token "${{ secrets.SLACK_TOKEN }}" \
            --slack-channel "#pavantest"
          exit 1
        fi